# Generated by Django 4.2.4 on 2024-02-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_agents'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agents',
            table='agents',
        ),
    ]
