# Generated by Django 4.2.4 on 2024-02-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_agents_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='info',
        ),
    ]
