# Generated by Django 4.2.4 on 2024-02-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_remove_agents_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='agent',
            new_name='title',
        ),
    ]
