# Generated by Django 4.2.4 on 2024-02-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_rename_agent_agents_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
