# Generated by Django 4.2.4 on 2024-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_agents_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'agency_requests',
            },
        ),
    ]
