# Generated by Django 4.2.4 on 2024-02-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
